#!/usr/bin/env python
# -*- encoding:utf8 -*-

import os, re

def weight(pb_m, pb):
	pb['weight'] = 1
	if len(pb['depends']) > 0:
		for dep in pb['depends']:
			pb['weight'] += weight(pb_m, pb_m[dep])
	return pb['weight']


def main():
	re_import = re.compile('import\s"\w+.proto";')
	re_impname = re.compile('"\w+.')

	pb_m = {}
	for filename in os.listdir("."):
		msg_name = filename[:-6] + '_pb'
		filetype = filename[-6:]
		if filetype == ".proto":
			f = open(filename)
			buf = f.read()
			f.close()

			pb_m[msg_name] = {}
			pb_m[msg_name]['name'] = msg_name
			pb_m[msg_name]['depends'] = []

			for r in re_import.finditer(buf):
				if r:
					imp = r.group()
					imp_name = re_impname.search(imp).group()[1:-1] + '_pb'
					pb_m[msg_name]['depends'].append(imp_name)

	for pb in pb_m.values():
		weight(pb_m, pb)

	lst = sorted(pb_m.values(), key = lambda x:(x['weight'], x['name']))

	buf = '---- Generated By reqlist.py Do not Edit\n\n-- protocols\n\n'
	for pb in lst:
		# print(pb['name'], pb['weight'])
		buf += 'require("dragon/core/io/protocol/' + pb['name'] + '.lua")'
		if len(pb['depends']) > 0:
			buf += ' -- depend: ' + ', '.join(pb['depends']) + '\n'
		else:
			buf += '\n'
	f = open('pb_includes.lua', 'w')
	f.write(buf)
	f.close()


if __name__ == "__main__":
	main()